language: node_js
node_js:
- '6'
- 'node'
env:
  global:
  - secure: "RTFlZNQJ5Ko/VIdXIMumHe5m8WY8o/KoD84TmkqEki+YhxcCtBqgJ+J7Hp4yTbxl4xMrbfocRT5VdQdCySGOsdZ4CrhMduLO94fWjEOzfuSI7JVaOVUKkdP1XlwXJe0p2cmSkv6D2lifekkHA7OySfaBJsmGJpq+73kWTcvxbpA="
  matrix:
  - MAILOSAUR_BASE_URL=https://mailosaur.com/api/ MAILOSAUR_SMTP_HOST=mailosaur.io
  - MAILOSAUR_BASE_URL=https://next.mailosaur.com/api/ MAILOSAUR_SMTP_HOST=ms-smtp.uk
notifications:
  slack: mailosaur:CsJ9RruwjqHPKr1Iugk8GDtX
