language: node_js
node_js:
- node
- iosjs
- '6'
- '5'
- '4'
env:
  matrix:
    secure: B1+MwvCBY8Q3GjVhBmP40hPBem5a/p2g5qDJeVxQNcb1yy6HSlgF2Me6tBlhGSwJqF3Ioqgth9aBodw6yfHRKkawXwNwtiV5pUw4HjvG+Up5QxYA2qAZgccUuatoyc+PdozT40j7Fz1YhLW8ok4h3Jk3IxuNqphk7l6XSpI88UQ=
