language: node_js
node_js:
- '6'
env:
  global:
    secure: G7CkYm69S9JKbw5Ndsfn1IXhCCRVg4vdfeGehFbghAukzmO4PjV77FqD7DJtlun8RdtYe0fIiC2VjT7FvVbaDEM+WaqusZ7C9d9Y3MqrmSBTJl4+MGNWfZMaap36RnGGOANcKDjkeca5a4oKiR0pZ9AI9A30Tn0tAxqA49U4xTc=
  matrix:
    MAILOSAUR_BASE_URL=https://mailosaur.com/api/ MAILOSAUR_SMTP_HOST=mailosaur.io
